### ISSUE TITLE
文字量が多い場合の見せ方

### ISSUE THREAD

**Issue by yokinist** [codeforyouth/vs-covid19#14]
## 改善詳細
- レイアウトが崩れかけているので以下の箇所は対応必要
  - 時期
  - 対象者
[![Image from Gyazo](https://i.gyazo.com/67eb8dcf3cb4c9ed1a4cb2074a05885c.png)](https://gyazo.com/67eb8dcf3cb4c9ed1a4cb2074a05885c)

**Comment by sensu-watson** [comment]
やります。Assigneesに追加お願いします。
